import type { Metadata } from 'next';
import { publicEnv } from '@/lib/env';
import { SITE } from '@/lib/siteConfig';

/**
 * Metadata for public pages, built one way everywhere.
 *
 * ## Why a helper and not a `metadata` object per page
 *
 * Next merges metadata **shallowly**: a page that sets `openGraph` replaces the
 * layout's `openGraph` entirely, and a page that does not set it inherits the
 * layout's — including its `og:title`. So without a helper, every page either
 * repeats the full Open Graph block or silently shares the home page's share
 * preview. This builds the whole set from four facts a page actually knows.
 *
 * What every public page gets:
 * - `<title>` (the root layout's template appends the brand) and a description;
 * - a canonical URL, so `www.`, a `*.vercel.app` alias or a `?utm=` link all
 *   count as this one address;
 * - Open Graph and Twitter cards with an image, so a shared link has a preview.
 *
 * Description length: aim for 120–160 characters. Shorter wastes the space a
 * search result gives you; longer is cut off mid-sentence.
 */

/** Generated by `src/app/og/route.tsx`: the brand card used when a page has no image of its own. */
export const DEFAULT_OG_IMAGE = {
  url: '/og',
  width: 1200,
  height: 630,
  alt: `${SITE.name} — ${SITE.tagline}`,
};

/** For pages that must never appear in search: gated content, password resets. */
export const NO_INDEX: Metadata['robots'] = { index: false, follow: false };

type PageSeo = {
  /** The page's own name. The root layout appends " — {brand}". */
  title: string;
  /**
   * Use the title as-is, without the brand suffix. Only for the home page,
   * whose title already leads with the brand.
   */
  absoluteTitle?: boolean;
  description: string;
  /** The page's path, e.g. `/kontakt`. Becomes the canonical URL. */
  path: string;
  /** Absolute URL, or a path under `public/`. Defaults to the brand card. */
  image?: { url: string; alt: string } | null;
  /** `article` for blog posts; everything else is a `website`. */
  type?: 'website' | 'article';
  /** ISO date, for articles. */
  publishedTime?: string;
  /** Keep this page out of search results. */
  noIndex?: boolean;
};

export function pageMetadata(seo: PageSeo): Metadata {
  const image = seo.image ?? DEFAULT_OG_IMAGE;
  const robots = seo.noIndex || !publicEnv.isIndexable ? NO_INDEX : undefined;

  return {
    title: seo.absoluteTitle ? { absolute: seo.title } : seo.title,
    description: seo.description,
    alternates: { canonical: seo.path },
    openGraph: {
      type: seo.type ?? 'website',
      siteName: SITE.name,
      locale: 'bs_BA',
      url: seo.path,
      // The share card shows the site name separately, so the brand suffix
      // would only repeat it.
      title: seo.title,
      description: seo.description,
      images: [image],
      ...(seo.publishedTime && { publishedTime: seo.publishedTime }),
    },
    twitter: {
      card: 'summary_large_image',
      title: seo.title,
      description: seo.description,
      images: [image.url],
    },
    // Left out entirely rather than set to `undefined`, so a page can never
    // switch indexing back on over the root layout's preview-deployment block.
    ...(robots && { robots }),
  };
}

/**
 * Fits authored text (a course description) into a meta description: one
 * line, at most `max` characters, cut at a word boundary with an ellipsis
 * rather than mid-word. Returns `null` for empty text so the caller can fall
 * back to something written for the purpose.
 */
export function metaDescription(text: string | null | undefined, max = 160): string | null {
  const flat = text?.replace(/\s+/g, ' ').trim();
  if (!flat) return null;
  if (flat.length <= max) return flat;

  const cut = flat.slice(0, max - 1);
  const lastSpace = cut.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[\s,.;:–—-]+$/, '')}…`;
}

/** `/kontakt` → `https://katedra.ba/kontakt`. For structured data, which needs absolute URLs. */
export function absoluteUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return `${publicEnv.siteUrl}${path.startsWith('/') ? path : `/${path}`}`;
}

/** The organisation behind the site, as schema.org describes it. Reused as the provider/publisher of courses and posts. */
export function organizationJsonLd() {
  const sameAs = SITE.social.map((profile) => profile.href).filter(Boolean);

  return {
    '@type': 'Organization',
    '@id': absoluteUrl('/#organization'),
    name: SITE.name,
    ...(SITE.company.legalName && { legalName: SITE.company.legalName }),
    url: absoluteUrl('/'),
    email: SITE.contact.email,
    telephone: SITE.contact.phone.tel,
    ...(SITE.company.address && { address: SITE.company.address }),
    ...(sameAs.length > 0 && { sameAs }),
  };
}
