import 'server-only';

import { unwrapMany, unwrapMaybe, unwrapOne } from '@/lib/api/errors';
import type { createServiceRoleClient } from '@/lib/supabase/service-role';

/**
 * Derived from the factory rather than hand-written as `SupabaseClient<Database>`
 * — the client carries more generic parameters than that, and spelling only the
 * first one collapses every table lookup to `never`.
 */
type ServiceClient = ReturnType<typeof createServiceRoleClient>;

/**
 * Applies a progress flag for one module and returns the resulting row.
 *
 * `completed` is intentionally never passed: a database trigger recomputes it
 * from `quiz_done`/`task_done` against whether the module actually has a quiz
 * and/or task, so the value cannot drift no matter which route wrote it.
 *
 * Read-modify-write rather than a blind upsert — upserting `{quiz_done: true}`
 * alone would reset `task_done` back to its column default.
 */
export async function applyModuleProgress(
  svc: ServiceClient,
  input: { moduleId: string; studentId: string; quizDone?: boolean; taskDone?: boolean },
) {
  const { moduleId, studentId, quizDone, taskDone } = input;

  const existing = unwrapMaybe(
    await svc
      .from('module_progress')
      .select('*')
      .eq('module_id', moduleId)
      .eq('student_id', studentId)
      .maybeSingle(),
  );

  if (existing) {
    return unwrapOne(
      await svc
        .from('module_progress')
        .update({
          quiz_done: quizDone ?? existing.quiz_done,
          task_done: taskDone ?? existing.task_done,
        })
        .eq('id', existing.id)
        .select()
        .single(),
    );
  }

  return unwrapOne(
    await svc
      .from('module_progress')
      .insert({
        module_id: moduleId,
        student_id: studentId,
        quiz_done: quizDone ?? false,
        task_done: taskDone ?? false,
      })
      .select()
      .single(),
  );
}

/**
 * Issues a certificate when every module of the course is complete for this
 * student. Idempotent: the unique (course_id, student_id) index means a repeat
 * call is a no-op rather than a duplicate.
 *
 * The existence of the certificate row IS the "course completed" signal — there
 * is no separate course_progress table.
 */
export async function maybeIssueCertificate(
  svc: ServiceClient,
  input: { courseId: string; studentId: string },
): Promise<{ issued: boolean; certificateId: string | null }> {
  const { courseId, studentId } = input;

  const moduleIds = unwrapMany(
    await svc.from('modules').select('id').eq('course_id', courseId),
  ).map((m) => m.id);

  // A course with no modules is not "completed" — it is unfinished content.
  if (moduleIds.length === 0) return { issued: false, certificateId: null };

  const completed = unwrapMany(
    await svc
      .from('module_progress')
      .select('module_id')
      .eq('student_id', studentId)
      .eq('completed', true)
      .in('module_id', moduleIds),
  );

  if (completed.length < moduleIds.length) return { issued: false, certificateId: null };

  const existing = unwrapMaybe(
    await svc
      .from('certificates')
      .select('id')
      .eq('course_id', courseId)
      .eq('student_id', studentId)
      .maybeSingle(),
  );

  if (existing) return { issued: false, certificateId: existing.id };

  // readable_id is generated by a column default backed by a sequence, so
  // concurrent issues cannot collide.
  const inserted = unwrapOne(
    await svc
      .from('certificates')
      .insert({ course_id: courseId, student_id: studentId })
      .select('id')
      .single(),
  );

  return { issued: true, certificateId: inserted.id };
}

/** Resolves the course a module belongs to. */
export async function getCourseIdForModule(svc: ServiceClient, moduleId: string): Promise<string> {
  const row = unwrapOne(await svc.from('modules').select('course_id').eq('id', moduleId).single());
  return row.course_id;
}
